name: Click Game Backend CI


on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main



jobs:

  test:

    runs-on: ubuntu-latest


    steps:

      # ------------------------
      # Checkout
      # ------------------------

      - name: Checkout repository
        uses: actions/checkout@v4



      # ------------------------
      # Python
      # ------------------------

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.13"



      # ------------------------
      # Install dependencies
      # ------------------------

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          pip install -r requirements.txt

          pip install -r requirements-test.txt



      # ------------------------
      # Run tests + coverage
      # ------------------------

      - name: Run tests
        run: |
          pytest \
            tests \
            --cov=backend \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-report=html \
            --cov-fail-under=90



      # ------------------------
      # Upload coverage
      # ------------------------

      - name: Upload coverage report
        uses: actions/upload-artifact@v4

        with:
          name: coverage-report

          path: |
            htmlcov/
            coverage.xml